### ISSUE TITLE
Sound null safety is currently missing.

### ISSUE THREAD

**Issue by olevabel** [cleverpush/cleverpush-flutter-sdk#11]
SDK 1.7.0 is missing sound null safety, so we need to run `flutter run` and `flutter build` with `--no-sound-null-safety` flag.

Please add sound null safety on future release.

**Comment by gbhrdt** [comment]
Hi @olevabel  we already released version 1.8.0 with null sound safety support :-)

**Comment by olevabel** [comment]
Confirming that it works as expected.
