### ISSUE TITLE
iOS: NotificationOpenedHandler not called when app not running in background

### ISSUE THREAD

**Issue by KMIxx** [cleverpush/cleverpush-flutter-sdk#17]
Hello

I'm unable to get a callback set with "setNotificationOpenedHandler" when testing push notifications in iOS. The notification is shown as expected with correct data but clicking on it does not invoke the callback. Android works as expected.

Prerequisites:
1. The app needs to be built in release mode (command line argument "--release")
2. The app can not be running in the background, it needs to be swiped from recents screen (everything works as expected when app is running in the background)

In my case the app was built with CI using the following command:
`flutter build ipa --export-options-plist=/Users/builder/export_options.plist --build-number=$PROJECT_BUILD_NUMBER --build-name=$APP_VERSION_NAME --flavor staging --release -t lib/main-staging.dart`

When monitoring the logs i can see the following (in xCode menu, click "Window -> Devices and Simulators -> Select device -> Open Console"):

1. I see that push is received with correct custom data which can be processed by the app (these log lines are received before app is starting)
2. Then app is started and cleverpush is successfully initiliazed
3. That's it, the callback is not called after app is initialized and the debug lines do not print anything inside the callback.

You can find logs here:
[cleverpush_logs.txt](https://github.com/cleverpush/cleverpush-flutter-sdk/files/7109462/cleverpush_logs.txt)

**Comment by gbhrdt** [comment]
This should be fixed in 1.9.1 which has just been released 👍 .
