### ISSUE TITLE
Android project repository issue

### ISSUE THREAD

**Issue by KMIxx** [cleverpush/cleverpush-flutter-sdk#23]
Hey @gbhrdt ! Our CI build is now failing with the following error:

```

FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:mergeStagingDebugAssets'.

> Could not resolve all files for configuration ':app:stagingDebugRuntimeClasspath'.

   > Could not resolve com.google.android.gms:play-services-base:[10.2.1, 17.6.99].

     Required by:

         project :app > project :cleverpush_flutter > com.cleverpush:cleverpush:1.16.1

      > Failed to list versions for com.google.android.gms:play-services-base.

         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml.

            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml'.

               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml'.

                  > Read timed out
```

I have a feeling that it's caused by the fact that jCenter is now in read only mode + will be ditched at some point next year. I'm not 100% sure why this issue came up now because that particular library has not been updated since February: https://mvnrepository.com/artifact/com.google.android.gms/play-services-base?repo=google

Could you update the dependencies in the SDK level and point them to mavenCentral?
I currently see that the repositories in the SDK level are defined as:

```
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
```

If possible we could remove "jcenter()" or if that is not possible at the moment then perhaps moving it below "mavenCentral()" would resolve the issue.

**Comment by gbhrdt** [comment]
Hi @KMIxx  
thanks for reporting. Currently we could not replicate it on our side.
Can you replicate it locally or only on your CI?

Could you check your own project level build.gradle that `google()` is at the top?

```
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
```

In our example project google() should be at the top and the GMS dependency which errors for you is hosted on Google's maven:
https://maven.google.com/web/index.html?q=play-services-base#com.google.android.gms:play-services-base

**Comment by KMIxx** [comment]
In my project i have the following order:
```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}
```
I could not replicate is locally, probably because the dependencies are cached on my machine, somewhere deep in Gradle directories. So it only happened in CI which builds with totally clean state, no caches at all.


Good news is that the error disappeared miraculously this morning, now it builds without problems. Not sure what was the root issue. Ill close this issue. Thanks for trying it out also!
