### ISSUE TITLE
Version 1.17.3 iOS dependency update problem

### ISSUE THREAD

**Issue by KMIxx** [cleverpush/cleverpush-flutter-sdk#32]
Hello!

I updated the Flutter SDK to 1.17.3 and after the update I cant run `pod update`/ `pod install`
I get the following error:

```
[!] CocoaPods could not find compatible versions for pod "CleverPush":
  In Podfile:
    CleverPush (= 1.22.1)

    cleverpush_flutter (from `.symlinks/plugins/cleverpush_flutter/ios`) was resolved to 1.17.3, which depends on
      CleverPush (= 1.22.10)

Specs satisfying the `CleverPush (= 1.22.1), CleverPush (= 1.22.10)` dependency were found, but they required a higher minimum deployment target.
```

After some debugging I think I found the issue. I think there is a typo in referenced Cleverpush library.
Inside file "cleverpush_flutter.podspec" there ise a reference to version "1.22.10" although the latest tag is "1.22.1".
Tags are mentioned here: https://github.com/cleverpush/cleverpush-ios-sdk/tags

`s.dependency 'CleverPush', '1.22.10'` should be ` s.dependency 'CleverPush', '1.22.1'`?

Reference:  https://github.com/cleverpush/cleverpush-flutter-sdk/blob/master/ios/cleverpush_flutter.podspec

**Comment by gbhrdt** [comment]
Hi @KMIxx  thanks for pointing this out, it was indeed a typo! We just release `1.17.4` which will resolve that issue :).
