### ISSUE TITLE
documentation: mention the googleservice disableVersionCheck

### ISSUE THREAD

**Issue by thekorn** [cleverpush/cleverpush-flutter-sdk#35]
Hi,
I'd be nice if the documentation on https://developers.cleverpush.com/docs/sdks/flutter/setup could either mention the `googleServices { disableVersionCheck = true }` setting for android, or at least refer to the troubleshooting section of the android SDK https://developers.cleverpush.com/docs/sdks/android/troubleshooting

**Comment by gbhrdt** [comment]
@thekorn  Thanks for the suggestion! We just updated the Flutter troubleshooting section and will keep improving in the future :-).
