### ISSUE TITLE
Chat theming issue

### ISSUE THREAD

**Issue by KMIxx** [cleverpush/cleverpush-flutter-sdk#38]
Hello!

Thanks for all the nice work so far. I have encountered 2 issues with the Chat feature:
1. Setting chat brand colour via `CleverPush.shared.setBrandingColor("#FF0000")` only works on Android  
2. The text color is not visible inside the chat bubble, maybe it's because the text and bubble are the same colour?

Can you reproduce these issues?
I read the [documentation](https://developers.cleverpush.com/docs/sdks/flutter/chat) for the chat but I can't find any other ways to change the colour.

I'm running on `cleverpush_flutter: ^1.21.0`

My Android device (shows red colour correctly but the text is missing)
![cp_chat_android](https://user-images.githubusercontent.com/957352/231717404-0ea20bef-f5b7-45fc-ada2-cce1e446bc45.png)

My iOS device (shows the wrong colour, should be red + the text missing)
![cp_chat_ios](https://user-images.githubusercontent.com/957352/231717631-c34ba839-4684-4624-b774-31b8a28eb5a3.jpeg)

**Comment by gbhrdt** [comment]
Hi @KMIxx thanks for raising that issue. We are currently looking into it and will get back ASAP.

**Comment by gbhrdt** [comment]
Hi @KMIxx  can you please check again on your side if this is fixed? We just optimized a few things on our backend.

**Comment by KMIxx** [comment]
Hey

There seems to be an issue with pod install now, I'm getting:
```
[!] CocoaPods could not find compatible versions for pod "CleverPush":
  In snapshot (Podfile.lock):
    CleverPush (= 1.26.1)

  In Podfile:
    CleverPush

    cleverpush_flutter (from `.symlinks/plugins/cleverpush_flutter/ios`) was resolved to 1.21.1, which depends on
      CleverPush (= 1.26.6)


You have either:
 * changed the constraints of dependency `CleverPush` inside your development pod `cleverpush_flutter`.
   You should run `pod update CleverPush` to apply changes you've made.
```

If I manually modify file `cleverpush_flutter.podspec` and change 
 ```
s.dependency 'CleverPush', '1.26.6'
```
to the previous version
```
s.dependency 'CleverPush', '1.26.1'
```
then it compiles again, can you reproduce this?

**Comment by gbhrdt** [comment]
Hi @KMIxx  please try to remove your `ios/Podfile.lock` file and run `pod install`

**Comment by KMIxx** [comment]
Unfortunately that does not help. Maybe it's because there is no iOS library with release tag `1.26.6`?

I checked [iOS releases](https://github.com/cleverpush/cleverpush-ios-sdk/releases) and there is no version `1.26.6` in here.
Versions `1.26.5` and `1.26.7` are present.

**Comment by KMIxx** [comment]
Got it working, thanks for the help! I misread your message and only deleted `pubspec.lock` although you suggested to delete `Podfile.lock` (+ the error indicated to that file). Now iOS build is OK + the color issue seems to be solved.
