### ISSUE TITLE
Android dependency Error

### ISSUE THREAD

**Issue by cschellhas** [cleverpush/cleverpush-flutter-sdk#4]
Hi now gettings this error on Android building

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[16.0.
  0, 17.0.99]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.cleverpush:cleverpush:1.0.0 -> com.google.android.gms:play-services-location@[16.0.0, 17.0.99], 
  but play-services-location version was 16.0.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.android.gms:play-services-location@16.0.0
  -- Project 'app' depends on project 'cleverpush_flutter' which depends onto com.cleverpush:cleverpush@1.0.0

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

With "googleServices.disableVersionCheck = true" I even get more errors.

**Comment by gbhrdt** [comment]
Hi @cschellhas  could you please post your `pubspec.yaml` file contents? I will then look into it. Probably there is some dependency conflict here.

**Comment by cschellhas** [comment]
`name: osthessennews
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  get_it: ^4.0.2
  stacked: ^1.5.5
  shared_preferences: ^0.5.7
  url_launcher: ^5.4.5
  share: ^0.6.4
  package_info: ^0.4.0+17
  webview_flutter: ^0.3.22+1

    #firebase
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  firebase_messaging: ^6.0.16
  firebase_dynamic_links: ^0.5.1
  #remove on release
  firebase_performance: ^0.3.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/placeholder.png
    - assets/termine.png`

**Comment by gbhrdt** [comment]
Hi, could you try to disable `firebase_messaging` ? If that doesn't help try to disable the other `firebase_..` plugins one by one so we see which one causes this dependency conflict.
