### ISSUE TITLE
Notifications are delivered after the "expiry time"

### ISSUE THREAD

**Issue by stefanschaller** [cleverpush/cleverpush-flutter-sdk#54]
`flutter --version` output: 

```
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (vor 6 Monaten) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
```

Test device: 
Samsung A52a 5G

We added the settings "The expiry date is enabled by default → Do not deliver notifications after **12** hours"

<img width="488" alt="Bildschirmfoto 2024-04-08 um 14 06 13" src="https://github.com/cleverpush/cleverpush-flutter-sdk/assets/30521865/7b26890f-6846-4899-ab4d-482b8b1bdba7">

The actual output shows that we also receive notifications that are older than the 12 hours. 
Our test included one push each hour and turn on the device after 24 hours:

We received 24 pushes, but the expected output was 12, since the other 12 should be expired and shouldn't be displayed.
 
![318767340-8b10dcd0-ed8b-4801-90a4-649c70b2c318](https://github.com/cleverpush/cleverpush-flutter-sdk/assets/30521865/f7a721e1-d31e-471c-9e47-62970371e041)

**Comment by gbhrdt** [comment]
Thanks @stefanschaller the underlying issue is a configuration issue, I will reply to you privately via mail.
