### ISSUE TITLE
iOS Application written using Flutter crashing upon receiving test push.

### ISSUE THREAD

**Issue by olevabel** [cleverpush/cleverpush-flutter-sdk#8]
Hi! 

We are developing Flutter application and integrating your Flutter SDK. We have been able to setup the app with Cleverpush, but upon receiving test push from your console we are getting a crash. Stacktrace can be found below. Our application is currently your sample app to test the integration.

Stacktrace of the crash:

`Unsupported value: <CPNotification: 0x28376af80> of type CPNotification
2021-07-29 10:50:18.835037+0300 Runner[13036:1528986] *** Assertion failure in -[FlutterStandardWriter writeValue:], FlutterStandardCodec.mm:330
2021-07-29 10:50:18.836044+0300 Runner[13036:1528986] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x1af2e4298 0x1c303e480 0x1af1f1cc8 0x1b0529128 0x104ab1520 0x104ab1a24 0x104aae874 0x104413704 0x10441310c 0x1043d5618 0x1043ef438 0x1b1ba1ae4 0x1b10a4154 0x1b10a520c 0x1b16c39d0 0x1bdd8a504 0x1bddb2ab4 0x1bdd97420 0x1bddb2a00 0x10683932c 0x10683c7e4 0x1bddd5e04 0x1bddd5acc 0x1bddd5fa0 0x1af2638f0 0x1af2637f0 0x1af262b44 0x1af25d060 0x1af25c818 0x1c5962570 0x1b1b880e8 0x1b1b8d664 0x1043b3dd8 0x1aef3b140)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
terminating with uncaught exception of type NSException`

Once again I will point out that we are using example app from here: https://github.com/cleverpush/cleverpush-flutter-sdk/blob/master/example/lib/main.dart.

**Comment by gbhrdt** [comment]
Hi @olevabel  thanks for letting us know! We were able to replicate the issue on our side and will probably deploy a fix by tomorrow. I will update you asap.

**Comment by gbhrdt** [comment]
Hi @olevabel  sorry for the delay. We have just released SDK v1.7.0 which should resolve the issue. Let me know if you still encounter anything else. 👍
